version: "3.7"

services:
  # Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./storage/public/usersAvatar:/var/www/storage/public/usersAvatar
    depends_on:
      - db
      - redis
      - npm
    networks:
      - laravel

  # Nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./storage:/var/www/storage
    networks:
      - laravel

  # Node.js (Vite)
  npm:
    image: node:latest
    container_name: npm
    restart: always
    volumes:
      - ./:/var/www
    ports:
      - "3000:3000"
    working_dir: /var/www
    command: ["npm", "run", "dev"]  # Comando para iniciar o Vite
    networks:
      - laravel

  # MySQL
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - laravel

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
    networks:
      - laravel

  # Redis
  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
